___TERMS_OF_SERVICE___

By creating or modifying this file you agree to Google Tag Manager's Community
Template Gallery Developer Terms of Service available at
https://developers.google.com/tag-manager/gallery-tos (or such other URL as
Google may provide), as modified from time to time.


___INFO___

{
  "displayName": "TNCiD - The Newco",
  "categories": [
    "ADVERTSING",
    "ANALYTICS"
  ],
  "description": "The official TNCid template. Quickly and easily install the tracking script, events, and custom variables",
  "securityGroups": [],
  "id": "cvt_temp_public_id",
  "type": "TAG",
  "version": 1,
  "brand": {
    "displayName": "TheNewco",
    "id": "github.com_TheNewco",
    "thumbnail": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAADGCAYAAAA9kQlSAAAACXBIWXMAACE4AAAhOAFFljFgAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAtrSURBVHgB7d3PchPJHQfwb4+Fd7O1tdHWkqrcGG65ISoFyy3DEwQKcgibKsQTQJ4A+QmAJ0BbBSSVwNq+5ebZGyEH7Cfw7DlQcYraDWtJ0+mfRirbkkYeTc9oWuPvp6qXRX/Gxvq6u6e7p0fBDS1TbqAcnZT/H9syZRfZ+Ka0ZzwejkpWTVPuI/l3t0bHFQemRKPvZ3v0vVEGbVN0SeW4Wc8/RnZByjE6Gd8vwXmE7N/7PmYHlia0UV2A/oPsAuQPkI8kEHn+DQ/hKA8ktUKAcvmm7OCoqVpUB46GiAFK3EW5OsgfnuPHCOAYBighHfgmyuHj9IBGo3Jwyuucq4UacIOcbYRznveRNAGTQlPuwZ6ER0LURfE6c54LkXz/0bHH2kg62rMCHSD5WUSghfiY3bncWfA48zqqWY4VYPFOdFrHeT/H15HyAA5hE3YkQPHNmBzPT3luXs0ZIhkHmuUSHMIAndRGsVopj0tfJ8R8WwsesxIM0Em/R7HSarQsI9/hgsesBAN0UgD70+3j0j7s/6ImGKBpbZRvkdFvp7lyGu8SGbPpoHrST+qmPO4MBmiaj6QpC1EtCUoRY1ylYhM2+2ynrKUltcMAzT6lLnturDYYoMS3E39fxgx9LRzvAzVR3hjDARzr/E2QZmxy/klqoRCrq8zPM5p8QJZXyqmlLqk8hR0f5c2Fjb+3x5heaDb5AQRYbC6sjXJ+Hll0Ud7nuY/RygBpwtpIfnhOjXBWYLIzPZ6hp2k+kl+aBxKg+yARYrqZvQua574EyKnJuYo9mfh7ANbM8/g8Cztp1phQG5SKATpJZsnDiceKnqGvFQZo2uRCrgDFztDXCgM0rYvpznQbNBMDNE3CM7ngi2djKbLOxstQfxf5RVgtGzg5leFj9aY2ZGyvi/zayPCLkzVAEVZ7WH9RUgNJTXT8FF4GFbewOrIsm50nyPIiNmGzSXgmJ1jZjM3AAKWbNbXxO9AJDFC6ENPNQBt0AgM03+SYkI/l8ZE+E+4MBmi+x6C5GKD5slxBmseXqAkG6HTbyC9tFeYFnM7HCmCATtdF/uW4UcrjPk5fJtJa8JiVWJXrwsYX2e3haH31stZZy9eQWijPOFCU8riE5wHmX8CYttBvD47Jsga2g3rIuz45QP6fz07Ke2TNtZ/ynodzvtayltl2kCEbvDI1mxDTUxtZSe0VzHhcjvUWSc26PTq+j6TmCVKOVVanPrez1ge6iOkpiqyeIJ8u0pvacVMmtZSEaRPz56C24NjlUWctQBGS0eQ8QQqRj3zgG7AXFXScQp3Vs7AISZBk84IfMr4nRP4QyYBk3hpMSAhvwsFlMWe9D9TFYtL6M1lIUyVBeIjFREjCY7s8oxQcB1pMF3Y6SJrPMMNrx03fZTgaHsGzsMXIh3ox5fGsIlOuIznjao3KhWPPyzjPLo4WtTmNAVpchGJEo7JKqxynsAkjKwwQWWGAyAoDRFZWohPdbOtmo/dzW6NxSUG3oLRvpvKG81LKdEQ1VKS13oPnhe+fNVa6U7pqnA7Q+T/1AhOUh+iZP01lqRAnT+ij1+jh6bD2lTIDfDq+/9U3h5F5bTg4t7Zx0FURqFRONmFS45jwbEJrM8mog0Xea2ok3wSt3ej19s/f6S066ksLci5AzfZha63Xe2vCY7/uRemOqZH2TSB9UCmcCtBX3/TvNnp4qwpcDyzHMoHcYYjK4UyApL9jmp4uSsAQlceJADXb//PNWVSWpaW5SYgavf4mqFBOBKjRazwtstlKp1vn7/zcARWm8gD96s5he9EzLStK3ZezPFAhKg9QrJZ+L/Rm4/DwAagQlQYo6ThXcAUma6HCVBogreM2qtFs9PstkLVKA6SgKrsHuooLGKik6gI0akIqqwW04m5jRaiuBjrs+aiQ5j0wClFZgBqeqvQDrKTzXkNcVL9MV14+NmeA+e+9ofU2/nXbqSGIygLU7/ejxtoaKrT8S2bUsNn0kZenfgnHVNcH+vTTiq95Us5erLdKKgvQQVcdqAqv9ZZlsCBrlY4DxdDfoyKejiv72nVS7UCi8rqoSC8ehCBrlQbo3bNzISrozGp43YO//iICWXNhPdDSN00aDHrObdS0qioP0Lvn64/1EjvTSuMJa5/iOLEicaCHGyiVToLa++lcB1QYJwJ08GJdxmT+jDIpHAwGg+sHW8r5PXdWiTNXZUhTZtqXcvomJjz9+PA6m67iOXVd2Ltnn3RQcE0kzdYwPC8+58hzCZy7MlVqov5gcLGIjrWcrg9+PHeZ4SmPk9fGS1Pz/vn6RXPGdC9fkFRoRimvv3/euMc+T7mcXs7x7xfrXfNHVxbf61jfUEqWwM64BMj0caBlcnSw3f/xky5DszwrsR5oNGIdjv/evKGb+HS0ovAjDhiY6qzkgrJRYBgaB3CLO7LCAJEVBoisMEBkhQEiKwwQWWGAyAoDRFZ4ZWpW1/4eoO+1sOZdQnx8s854z0ylhPjsQ4jw3pkb3GSATnPlVVs2pDKhaQ3rax0PL6w/ogLIrbp/+gL4+lUX6nADr/8Y4YxwtwkLnjaHJa9rmz5sXPuLjyvf7ZiwPJXNOTO9R6ONeH0fVzfPzA757tZAHz9vIfZ2cPXlrqkBdjHAHjwdmWKaiUZ08sV9HwPTrChlSuOCqSUCxLGPiboiMwlPvL4zvKlLLnEHV1818eZWuct0HbACTZhqmd/spPmQPMSSiXjiNd5RVHQMK+Pw2G//8sCEP8Dhh+vYrW/fiGdhkwbDqzZ8FMKE/9wXj1BjDNBxSYf5LoqkTL/o61e13VaYATqurD2rNR7hyt9quSssAzT225eya6uP0jRq2ZRxHGjMQ7nb/ipZy12/PYlYA43Z7F2YnY+aYYCETFNw299cGCChPd72ICcGSOgl3m6qZhggoTznts9dFQyQ0AXdS1XpJ9CDy2YOTA3LZ96XZgzoHircjbZsPI1PFNGB3sA/b3dOPBLelDmwLq5thmZy9y1q2FFnDZSw+2CVCcmbW53U51/fjExNVMuZeQaoCH29fepret4Wang5NgNUhMGH8NTX7EpzxpFomiXzep94DzXDAJEVBoisMEBkhQEiKwwQWWGAyAoDRFYYILLCAJEVBoisMEBkhQEiKwwQWWGAyAoDRFYYILLCAJEVBoisMEBkhQEiKwwQWWGAyAoDRFYYILLCAJEVBoisMEBkhQEiKwwQWWGAlkl5F1AzDFARst7cTnOLO5pF90+/TYLchyzrnQ9XCANUBJ3hFlHxerG3kXIEA5Sw3LtQtXDl1dPUp699J+HpoIa4zW9CAmS7U2sbV18FiPEEjXh3+JjcxxWNu4jruxM+AySUigrabNw3dfojxKOKfXgfV406YxMmdPwDKBcGSMhtxSkXBkiomAHKiQESr/8Qooa7yC8DAzSm9bcoX4SaYYDG1vQWyqRVaP7zPWqGARqTZkzJh1ySNXUPNcQAHacGGyjHxvCWTzXEAB0ntZDWT1AovTf3XmIrjgGa1FvroLjObgRv7fSZ+hXGAE2S+3p53nVYh8jUPHKcmjZdYwzQLPKhH3qXTQhyntrHG3hzu1X38Ah3J1M/NnZxrlfdmcvwDoNmhv3aZgfxoGN62PPX82gzEOmZwKm1x3h9K0p5lRkqiCPkpd2bcpH54izTxXJ20sFZFmw28bHfQt9rwYuPln7E3sFw+UYyml0nHVMeZnmhzlA6oLOmgwzZYB+IrDBAZIUBIisMEFlhgMgKA0RWGCCywgCRFQaIrDBAZIUBIisMEFlhgMgKA0RWGCCywgCRFQaIrDBAZIUBIisMEFlhgMgKA0RWsl5YeAlykR2dJZeyvCjrhYVEM7EJIysMEFlhgMgKA0RWGCCyIgEKQZTPrpzGB6bsgGhxN9eQ7AW4Z8pvTPk1iE4XmiK7x/3j/7fRtSWgErqsAAAAAElFTkSuQmCC"
  },
  "containerContexts": [
    "WEB"
  ]
}


___TEMPLATE_PARAMETERS___

[
  {
    "type": "TEXT",
    "name": "ProviderID",
    "displayName": "Provider ID (Generated by The Newco)",
    "simpleValueType": true,
    "notSetText": "Mandatory field",
    "valueValidators": [
      {
        "type": "NON_EMPTY"
      },
      {
        "type": "REGEX",
        "args": [
          "^(\\{){0,1}[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{4}\\-[0-9a-fA-F]{12}(\\}){0,1}$"
        ]
      }
    ],
    "valueHint": "Your Provider ID",
    "help": "Please, ask The Newco to create a dedicated ProviderID for you website(s) in the format of UUID:\n\u0027XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\u0027"
  },
  {
    "type": "RADIO",
    "name": "EventName",
    "displayName": "Event Name",
    "radioItems": [
      {
        "value": "standard",
        "displayValue": "Standard",
        "subParams": [
          {
            "type": "SELECT",
            "name": "StandardEventName",
            "selectItems": [
              {
                "value": "pageview",
                "displayValue": "pageview"
              },
              {
                "value": "add_to_cart",
                "displayValue": "add_to_cart"
              },
              {
                "value": "view_cart",
                "displayValue": "view_cart"
              },
              {
                "value": "lead",
                "displayValue": "lead"
              },
              {
                "value": "purchase",
                "displayValue": "purchase"
              },
              {
                "value": "checkout",
                "displayValue": "checkout"
              },
              {
                "value": "view_product",
                "displayValue": "view_product"
              }
            ],
            "simpleValueType": true,
            "defaultValue": "pageview",
            "displayName": "Event Name"
          }
        ]
      },
      {
        "value": "custom",
        "displayValue": "Custom",
        "subParams": [
          {
            "type": "TEXT",
            "name": "CustomEventName",
            "displayName": "Event Name",
            "simpleValueType": true,
            "defaultValue": ""
          }
        ]
      }
    ],
    "simpleValueType": true
  },
  {
    "type": "CHECKBOX",
    "name": "EnableCustomerData",
    "checkboxText": "Enable Customer Data",
    "simpleValueType": true
  },
  {
    "type": "GROUP",
    "name": "CustomerDataSection",
    "displayName": "Customer Data Properties",
    "groupStyle": "ZIPPY_CLOSED",
    "subParams": [
      {
        "type": "SIMPLE_TABLE",
        "name": "CustomerData",
        "displayName": "",
        "simpleTableColumns": [
          {
            "defaultValue": "",
            "displayName": "Name",
            "name": "name",
            "type": "SELECT",
            "selectItems": [
              {
                "value": "e",
                "displayValue": "Email"
              },
              {
                "value": "pc",
                "displayValue": "Phone With Country Prefix"
              },
              {
                "value": "pn",
                "displayValue": "Phone Without Country Prefix"
              },
              {
                "value": "ex",
                "displayValue": "External User ID"
              },
              {
                "value": "crm",
                "displayValue": "CRM User ID"
              }
            ]
          },
          {
            "defaultValue": "",
            "displayName": "Value",
            "name": "value",
            "type": "TEXT"
          }
        ]
      }
    ],
    "enablingConditions": [
      {
        "paramName": "EnableCustomerData",
        "paramValue": true,
        "type": "EQUALS"
      }
    ]
  },
  {
    "type": "CHECKBOX",
    "name": "EnableCustomVariables",
    "checkboxText": "Enable Custom Variables",
    "simpleValueType": true
  },
  {
    "type": "GROUP",
    "name": "CustomVariablesSection",
    "displayName": "Custom Variables",
    "groupStyle": "ZIPPY_CLOSED",
    "subParams": [
      {
        "type": "SIMPLE_TABLE",
        "name": "CustomVariables",
        "displayName": "",
        "simpleTableColumns": [
          {
            "defaultValue": "",
            "displayName": "Name",
            "name": "Name",
            "type": "TEXT",
            "selectItems": [
              {
                "value": "e",
                "displayValue": "Email"
              },
              {
                "value": "pc",
                "displayValue": "Phone With Country Prefix"
              },
              {
                "value": "pn",
                "displayValue": "Phone Without Country Prefix"
              },
              {
                "value": "ex",
                "displayValue": "External User ID"
              },
              {
                "value": "crm",
                "displayValue": "CRM User ID"
              }
            ]
          },
          {
            "defaultValue": "",
            "displayName": "Type",
            "name": "Type",
            "type": "SELECT",
            "selectItems": [
              {
                "value": "string",
                "displayValue": "String"
              },
              {
                "value": "float",
                "displayValue": "Float"
              },
              {
                "value": "int",
                "displayValue": "Integer"
              },
              {
                "value": "uint",
                "displayValue": "Unsigned Integer"
              },
              {
                "value": "bool",
                "displayValue": "Boolean"
              },
              {
                "value": "json",
                "displayValue": "JSON or Array"
              }
            ],
            "macrosInSelect": false,
            "valueValidators": []
          },
          {
            "defaultValue": "",
            "displayName": "Value",
            "name": "Value",
            "type": "TEXT"
          }
        ]
      }
    ],
    "enablingConditions": [
      {
        "paramName": "EnableCustomVariables",
        "paramValue": true,
        "type": "EQUALS"
      }
    ]
  },
  {
    "type": "CHECKBOX",
    "name": "EnablePushDataLayerEvent",
    "checkboxText": "Enable Push dataLayer Event",
    "simpleValueType": true
  },
  {
    "type": "GROUP",
    "name": "PushDataLayerEvent",
    "displayName": "Push dataLayer event when TNCiD is available",
    "groupStyle": "ZIPPY_CLOSED",
    "subParams": [
      {
        "type": "TEXT",
        "name": "DataLayerEventName",
        "displayName": "Event to trigger",
        "simpleValueType": true,
        "defaultValue": "tncid-retrieved",
        "valueHint": "tncid-retrieved",
        "valueValidators": [
          {
            "type": "NON_EMPTY"
          }
        ],
        "notSetText": "You must set the Event name"
      }
    ],
    "enablingConditions": [
      {
        "paramName": "EnablePushDataLayerEvent",
        "paramValue": true,
        "type": "EQUALS"
      }
    ]
  },
  {
    "type": "CHECKBOX",
    "name": "EnableWindowCustomEventTrigger",
    "checkboxText": "Enable window CustomEvent trigger",
    "simpleValueType": true
  },
  {
    "type": "GROUP",
    "name": "WindowCustomEventTrigger",
    "displayName": "Trig window CustomEvent when TNCiD is available",
    "groupStyle": "ZIPPY_CLOSED",
    "subParams": [
      {
        "type": "TEXT",
        "name": "WindowCustomEventName",
        "displayName": "Event to trigger",
        "simpleValueType": true,
        "defaultValue": "tncid-retrieved",
        "valueHint": "tncid-retrieved",
        "valueValidators": [
          {
            "type": "NON_EMPTY"
          }
        ],
        "notSetText": "You must set the Event name"
      }
    ],
    "enablingConditions": [
      {
        "paramName": "EnableWindowCustomEventTrigger",
        "paramValue": true,
        "type": "EQUALS"
      }
    ]
  }
]


___SANDBOXED_JS_FOR_WEB_TEMPLATE___

var log = require('logToConsole');
log('data =', data);

const setInWindow = require('setInWindow');
const callInWindow = require('callInWindow');
const copyFromWindow = require('copyFromWindow');
const callLater = require('callLater');
const queryPermission = require('queryPermission');
const injectScript = require('injectScript');
const encodeUriComponent = require('encodeUriComponent');
let dataLayerCallback = ()=>{};
if (queryPermission('access_globals', 'readwrite', 'dataLayer')) {
  dataLayerCallback = (eventName, tncid) => {
    callInWindow('dataLayer.push', {
      event: eventName,
      tncid: tncid
    });
  };
}

const TNCObjectName = '__tnc';
const override = true;
const providerId = data.ProviderID;
const EventName = data.EventName=='standard' ? data.StandardEventName : data.CustomEventName.trim();
const customerData = data.CustomerData || [];
const customVariables = data.CustomVariables || [];
const DataLayerEventName = data.DataLayerEventName;
const WindowCustomEventName = data.WindowCustomEventName;
const url = 'https://run.tncid.app/tnc.min.js?providerId='+encodeUriComponent(providerId)+'&global='+encodeUriComponent(TNCObjectName)+'&autostart=true';

log('TNCObjectName = ', TNCObjectName);

var ObjectExists = ()=>typeof copyFromWindow(TNCObjectName+'.sendData')=='function';
var SuccessFunc = ()=>{
  setInWindow(TNCObjectName+'Loading', false, override);
  callInWindow(TNCObjectName+'Func', TNCObjectName, 'ready', onReady);
  data.gtmOnSuccess();
};

// reflect changes to window object
setInWindow(TNCObjectName+'Func', function(g, method, arg1, arg2, arg3){
  callLater(()=>{
    callInWindow(g+'.'+method, arg1, arg2, arg3);
  });
}, !override);

// Add a callback into in-page __tnc.ready
var onReady = function(){ 
  // Set main configs
  let config = customerData.reduce((p,item)=>{
    if (typeof item.value!=='undefined' && item.value!==null) {
      p[item.name] = item.value;
    }
    return p;
  }, {
    st: EventName
  });  
  callInWindow(TNCObjectName+'Func', TNCObjectName, 'setConfig', config);
  // Add custom variables
  (customVariables||[]).forEach(cv=>{
    log('CustomVariable received', cv);
    callInWindow(TNCObjectName+'Func', TNCObjectName, 'addCustomVariable', cv);
  });
  
  // Push dataLayer event
  if (DataLayerEventName) {
    log('Setting PushDataLayerEvent', DataLayerEventName);
    let listener = (res)=>{
      log('DataLayer Event triggering', DataLayerEventName, res.tncid);
      dataLayerCallback(DataLayerEventName, res.tncid);
    };

    callInWindow(TNCObjectName+'Func', TNCObjectName, 'on', 'data-sent', listener, true);
    log('data-sent listener set');
  }
  
  // Window CustomEvent trigger
  if (WindowCustomEventName) {
    log('WindowCustomEventName', WindowCustomEventName);
    let listenerCE = (res)=>{
      log('WindowCustomEvent triggering', WindowCustomEventName, res.tncid);
      callInWindow(TNCObjectName+'Func', TNCObjectName, 'CustomEvent', WindowCustomEventName, { tncid: res.tncid });
    };

    callInWindow(TNCObjectName+'Func', TNCObjectName, 'on', 'data-sent', listenerCE, true);
    log('data-sent listener set');
  }
};

function Init(err) {
  if (err) {
    log(err);
    return data.gtmOnFailure(err);
  }
  if (ObjectExists()) {
    return SuccessFunc();
  }

  var IsLoading = copyFromWindow(TNCObjectName+'Loading');
  if (IsLoading) {
    while(IsLoading) {
      IsLoading = copyFromWindow(TNCObjectName+'Loading');
    }
    return Init();
  }

  if (queryPermission('inject_script', url)) {
    setInWindow(TNCObjectName+'Loading', true, override);
    injectScript(url, Init, data.gtmOnFailure, 'TheNewcoID');
  } else {
    setInWindow(TNCObjectName+'Loading', false, override);
    Init('failed to load TNCiD tag');
  }
}
Init();


___WEB_PERMISSIONS___

[
  {
    "instance": {
      "key": {
        "publicId": "logging",
        "versionId": "1"
      },
      "param": [
        {
          "key": "environments",
          "value": {
            "type": 1,
            "string": "debug"
          }
        }
      ]
    },
    "clientAnnotations": {
      "isEditedByUser": true
    },
    "isRequired": true
  },
  {
    "instance": {
      "key": {
        "publicId": "inject_script",
        "versionId": "1"
      },
      "param": [
        {
          "key": "urls",
          "value": {
            "type": 2,
            "listItem": [
              {
                "type": 1,
                "string": "https://*.tncid.app/*"
              }
            ]
          }
        }
      ]
    },
    "clientAnnotations": {
      "isEditedByUser": true
    },
    "isRequired": true
  },
  {
    "instance": {
      "key": {
        "publicId": "access_globals",
        "versionId": "1"
      },
      "param": [
        {
          "key": "keys",
          "value": {
            "type": 2,
            "listItem": [
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "dataLayer"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "__tnc"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "dataLayer.push"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "__tnc.ready"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "__tnc.options"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "__tnc.options.autostart"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "__tnc.setConfig"
                  },
                  {
                    "type": 8,
                    "boolean": false
                  },
                  {
                    "type": 8,
                    "boolean": false
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "__tnc.on"
                  },
                  {
                    "type": 8,
                    "boolean": false
                  },
                  {
                    "type": 8,
                    "boolean": false
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "__tnc.sendData"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "__tnc.addCustomVariable"
                  },
                  {
                    "type": 8,
                    "boolean": false
                  },
                  {
                    "type": 8,
                    "boolean": false
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "__tncFunc"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  }
                ]
              },
              {
                "type": 3,
                "mapKey": [
                  {
                    "type": 1,
                    "string": "key"
                  },
                  {
                    "type": 1,
                    "string": "read"
                  },
                  {
                    "type": 1,
                    "string": "write"
                  },
                  {
                    "type": 1,
                    "string": "execute"
                  }
                ],
                "mapValue": [
                  {
                    "type": 1,
                    "string": "__tncLoading"
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": true
                  },
                  {
                    "type": 8,
                    "boolean": false
                  }
                ]
              }
            ]
          }
        }
      ]
    },
    "clientAnnotations": {
      "isEditedByUser": true
    },
    "isRequired": true
  }
]


___TESTS___

scenarios:
- name: Quick Test
  code: runCode();
setup: ''


___NOTES___

Created on 21/6/2023, 15:15:15


